import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
 weight: ['100', '300', '400', '500', '600', '700', '900'],
style: ['normal', 'italic'],
subsets: ['latin'],
  
   });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
        <footer className="border-t-1 border-white text-center text-xl py-4">
          
          CopyRight© TiPo 2024
        </footer>
      </body>
    </html>
  );
}
